### ISSUE TITLE
feat: function to crawl replies (comments) to each post of channel?

### ISSUE THREAD

**Issue by vicru** [Leibniz-HBI/tegracli#49]
Hi, is there a function built in `tegracli` to crawl not only the text of posts of a channel (`tegracli` does a great job in this respect) but actually to crawl all replies (comments) to each post of a telegram-channel?

`tegracli` yields the number of replies to a post (in the variable called `replies`). I have not found a way to actually crawl the text of those individual replies.

Thanks in advance for any insights.

**Comment by pekasen** [comment]
Hi,

`tegracli` does not (yet) have this functionality in a way which would make a larger collection of replies feasible: The `get`-command exposes the replies-parameter which can be used to retrieved replies to a single post. You could use an external loop over the post_ids you need and pass the ids in the `replies`-parameter.

However, I'd imagine another command to get the replies for a list of posts (comparable to the `hydrate`-command). Although, I am not sure about the timeline.

**Comment by pekasen** [comment]
Hi @vicru,

upon further investigation I found that Telegram indeed gives the count of replies in the field you mentioned, e.g.:

```yaml
{
  "id": 123,
  "replies": {
    "_": "MessageReplies",
    "replies": 3, 
    ...
  },
...
}
```
The above mentioned API-method can give you the replies, however, if you already crawled the channel history you should have the replies on your system!

Replies are marked by Telegram in the following way: replying to a post creates another post for the channel, thus, increasing the post count. Thus, that new posts very much looks like a regular posts. However, it has a field called `reply_to` in which the posts which was replied to is referenced via it's post number.

```yaml
{
  "id": 124,  # new message
  "reply_to": {
    "_": "MessageReplyHeader",
    "reply_to_msg_id": 123,  # referenced post id
    "reply_to_scheduled": false,
    "reply_to_peer_id": null,
    "reply_to_top_id": null
  },
  ...
}
```

I think the already existing functionality of `tegracli` is so far sufficient, as we get the data we want by getting the channel history. Happy to hear your thoughts.
